import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import "leaflet/dist/leaflet.css";
import StoreProvider from "./StoreProvider";
import AuthProvider from "./AuthProvider";

const sora = Sora({
     subsets: ["latin"],
     weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
     title: "Create Next App",
     description: "Generated by create next app",
};

export default function RootLayout({
     children,
}: Readonly<{
     children: React.ReactNode;
}>) {
     return (
          <html
               lang="en"
               className={`${sora.className} h-full antialiased`}
               suppressHydrationWarning
          >
               <body className="min-h-full flex flex-col">
                    <StoreProvider>
                         <ThemeProvider
                              attribute="class"
                              defaultTheme="system"
                              enableSystem
                              disableTransitionOnChange
                         >
                              <AuthProvider>{children}</AuthProvider>
                         </ThemeProvider>
                    </StoreProvider>
               </body>
          </html>
     );
}
